### ISSUE TITLE
Memory issue with numpy version >= 1.23

### ISSUE THREAD

**Issue by khsa1** [OSC/planet_mosaicking#1]
Running with `numpy` version 1.23.0 or greater causes the following error message:

```
Traceback (most recent call last):
  File "/home/khuvis.1/workspace/mosaicking_nasa/./mosaic.py", line 9, in <module>
    [x,y,z] = mosaicDEMTiles(fileNames)
  File "/home/khuvis.1/workspace/mosaicking_nasa/mosaicDEMTiles.py", line 149, in mosaicDEMTiles
    zsub = z[np.meshgrid(nrows, ncols)].T
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 386. GiB for an array with shape (2, 1500, 1500, 11500) and data type float64
```

Current workaround is to downgrade your version of `numpy` to 1.22 or older.

**Comment by khsa1** [comment]
Fixed with 56d628ba3c8eb39d025306d96b451af57c80665d.
